#!/bin/bash

function exit_on_error {
    echo -e "$1"
    exit 1
}

# Check if transcode is installed
#
which transcode >/dev/null || exit_on_error "This program requires the package \"transcode\""

# Defaults
#

OUTDIR="/home/fs/Music/$1/$2"
DVDDEV="/dev/sr0"

TITLE=1
TITLECOUNT=0
CHAPTERS=0
AUDIOTRACK=0
AUDIOPRESET=0
CONT=n

LAME_PRESET="insane"

# check the first XX MB of the DVD
CHECKSIZE=10
#CHECKSIZE=1

declare -a TITLEINFO
declare -a AUDIOINFO
#----------------------------------

mkdir -p $OUTDIR

echo "Reading DVD information..."

# get number of titles
#
TITLECOUNT=$(tcprobe -i ${DVDDEV} -H ${CHECKSIZE} 2>&1 | sed -n 's/.*DVD title [0-9][0-9]*\/\([^:]*\).*/\1/p')

if [[ 1 -lt $TITLECOUNT ]]; then
    # Get info about each title
    #
    for (( i=1; i<=${TITLECOUNT}; i++ )); do
        TITLEINFO[$i]=$(tcprobe -i ${DVDDEV} -H ${CHECKSIZE} -T ${i} 2>&1 | grep -E 'DVD title|audio track')
        # We only want to see lines with the titles now
        echo "${TITLEINFO[$i]}" | head -n1 | sed "s/\[[^]]*\]/[${i}]/"
    done

    # User chooses DVD title
    #
    while true; do
        read -e -p "Choose a title (1 to ${TITLECOUNT}) [1]: " TITLE
        [[ -z $TITLE ]] && TITLE=1
        # loop until we get a valid value
        [[ $TITLE =~ ^-?[0-9]+$ && $TITLE -le $TITLECOUNT ]] && break
    done
else
    TITLEINFO[1]=$(tcprobe -i ${DVDDEV} -H ${CHECKSIZE} -T 1 2>&1 | grep -E 'DVD title|audio track')
    echo "Only one DVD title present, ripping tracks from title ${TITLE}"
fi

echo

# Now get the number of chapters
#
CHAPTERS=$(echo "${TITLEINFO[$TITLE]}" | head -n1 | sed 's/.*DVD title [0-9][0-9]*\/[^:]*:\s\([0-9][0-9]*\).*/\1/')

# List Audio Tracks and try to choose the correct one
#
AUDIOCOUNT=$(echo "${TITLEINFO[$TITLE]}" | tail -n +2 | wc -l)

if [[ 1 -lt $AUDIOCOUNT ]]; then
    # extract the audioinfo lines from TITLEINFO
    AUDIOINFO=$(echo "${TITLEINFO[$TITLE]}" | tail -n +2 | sed 's/^\s*//g')
    # print the audioinfo lines
    # according to the tcprobe output the line that does _not_ end with
    # (*) is the default audio - probably what we want
    #
    j=0
    while read AI; do
        [[ $AI =~ ^.+\(\*\)$ ]] || AUDIOPRESET="${j}"
        echo "[${j}] ${AI}"
        let j++;
    done <<< "$AUDIOINFO"

    # read the user input
    while true; do
        read -e -p "Choose an audio track [${AUDIOPRESET}]: " AUDIOTRACK
        [[ -z $AUDIOTRACK ]] && AUDIOTRACK=$AUDIOPRESET
        [[ $AUDIOTRACK =~ ^-?[0-9]+$ && $AUDIOTRACK -le $AUDIOCOUNT ]] && break
    done
else
    echo "Only one audio track present, ripping audio track ${AUDIOTRACK}"
fi

echo

echo "DVD title: $TITLE
Chapters: $CHAPTERS
Audio Track: $AUDIOTRACK"

while true; do
        read -e -p "Start ripping $CHAPTERS audio tracks from DVD title $TITLE? [Y/n] " CONT
        [[ -z $CONT ]] && CONT="y"
        if [[ $CONT =~ ^[yY]$ ]]; then
            break
        else
            exit 1
        fi
    done

echo

for (( i=1; i<=${CHAPTERS}; i++ )); do
    if [[ $i -lt 10 ]]; then
        TRACKNO="0${i}"
    else
        TRACKNO="${i}"
    fi
    transcode -x null,dvd -y null,tcaud -i ${DVDDEV} -T $TITLE,${i},1 \
              -a ${AUDIOTRACK} -E 44100,16,2 --lame_preset ${LAME_PRESET} \
              -m ${OUTDIR}/${TRACKNO}.mp3
done

eject ${DVDDEV}

#Inspect DVD with following command

#    pg@pipoTower: ~$ tcprobe -i /dev/sr0

#    look for line where chapters is like following:

#    [dvd_reader.c] DVD title 1/1: 17 chapter(s), 1 angle(s), title set 1

#    Rip all titles to mp3 where for example {1..17} is the number of
#    chapters of your dvd

#    for i in {1..17};do
#      transcode -x null,dvd -y null,tcaud -i /dev/sr0 -T 1,$i,1 -a 0 -E 44100,16,2 --lame_preset medium -m ~/tmp/yourDestinationMp3File_chapter${i}.mp3;
#    done

#    For details of command:
#        -T title,chapter,angle (described by your tcprobe command in
#           point 1.)
#        -a audioTrackNumber
#        -i inputDevice
#        --lampe_preset can be: medium, standard, extreme refer to man
#                               transcode for further details
