#!/bin/bash

# TODO
#
# 1. Range of tracks to be ripped (1,2,4,5 | 2-12)
# 2. Basic tagging (Artist, Album, Year, Genre, Comment)
# 3. mp3gain
# 4. Command line parsing with GNU getopt


function exit_on_error {
    echo -e "$1"
    exit 1
}

trap "exit_on_error '\nCaught SIGTERM/SIGINT'" SIGTERM SIGINT
#trap "cleanup" ERR

# Check if transcode is installed
#
which transcode >/dev/null || exit_on_error "This program requires the package \"transcode\""



# Defaults
#

OUTDIR="$HOME/Music/$1/$2"
DVDDEV="/dev/sr0"

TITLE=1
TITLECOUNT=0
CHAPTERCOUNTER=0
CHAPTERID=0
AUDIOTRACK=0
AUDIOPRESET=0
CONT=n

LAME_PRESET="insane"

# check the first XX MB of the DVD
CHECKSIZE=10
#CHECKSIZE=1

declare -a TITLEINFO
declare -a CHAPTERS
declare -a AUDIOINFO
#----------------------------------

mkdir -p $OUTDIR

echo "Reading DVD information..."

# get number of titles
#
TITLECOUNT=$(tcprobe -i ${DVDDEV} -H ${CHECKSIZE} 2>&1) || exit_on_error "Fatal Error: Could not read DVD\n Make sure you have inserted a DVD and libdvdcss2 is installed"
TITLECOUNT=$(cat <<< $TITLECOUNT \
    | sed -n 's/.*DVD title [0-9][0-9]*\/\([^:]*\).*/\1/p')

if [[ 1 -lt $TITLECOUNT ]]; then
    # Get info about each title
    # Remove all lines except the one with DVD title and audio track
    # information
    #
    for (( i=1; i<=${TITLECOUNT}; i++ )); do
        TITLEINFO[$i]=$(tcprobe -i ${DVDDEV} -H ${CHECKSIZE} -T ${i} 2>&1 \
            | grep -E 'DVD title|audio track')
        # Get the amount of chapters for each title
        # We want the preset for the DVD title to be the one with the most
        # chapters $CHAPTERID
        #
        CHAPTERS[$i]=$(echo "${TITLEINFO[$i]}" | head -n1 \
             | sed 's/.*DVD title [0-9][0-9]*\/[^:]*:\s\([0-9][0-9]*\).*/\1/')
        if [[ ${CHAPTERS[$i]} -gt $CHAPTERCOUNTER ]]; then
            CHAPTERCOUNTER=${CHAPTERS[$i]}
            CHAPTERID=$i
        fi

        # We only want to display lines with the titles now
        echo "${TITLEINFO[$i]}" | head -n1 | sed "s/\[[^]]*\]/[${i}]/"
    done

    # User chooses DVD title, preset is CHAPTERID
    #
    while true; do
        read -e -p "Choose a title (1 to ${TITLECOUNT}) [$CHAPTERID]: " TITLE
        [[ -z $TITLE ]] && TITLE=$CHAPTERID
        # loop until we get a valid value
        [[ $TITLE =~ ^-?[0-9]+$ && $TITLE -le $TITLECOUNT ]] && break
    done
else
    TITLEINFO[1]=$(tcprobe -i ${DVDDEV} -H ${CHECKSIZE} -T 1 2>&1 | grep -E 'DVD title|audio track')
    echo "Only one DVD title present, ripping tracks from title ${TITLE}"
fi

echo

# List Audio Tracks and try to choose the correct one
#
AUDIOCOUNT=$(echo "${TITLEINFO[$TITLE]}" | tail -n +2 | wc -l)

if [[ 1 -lt $AUDIOCOUNT ]]; then
    # extract the audioinfo lines from TITLEINFO
    AUDIOINFO=$(echo "${TITLEINFO[$TITLE]}" | tail -n +2 | sed 's/^\s*//g')
    # print the audioinfo lines
    # according to the tcprobe output the line that does _not_ end with
    # (*) is the default audio - probably what we want
    #
    j=0
    while read AI; do
        [[ $AI =~ ^.+\(\*\)$ ]] || AUDIOPRESET="${j}"
        echo "[${j}] ${AI}"
        let j++;
    done <<< "$AUDIOINFO"

    # read the user input
    while true; do
        read -e -p "Choose an audio track [${AUDIOPRESET}]: " AUDIOTRACK
        [[ -z $AUDIOTRACK ]] && AUDIOTRACK=$AUDIOPRESET
        [[ $AUDIOTRACK =~ ^-?[0-9]+$ && $AUDIOTRACK -le $AUDIOCOUNT ]] && break
    done
else
    echo "Only one audio track present, ripping audio track ${AUDIOTRACK}"
fi

echo

echo "DVD title: $TITLE
Chapters: ${CHAPTERS[$TITLE]}
Audio Track: $AUDIOTRACK"

while true; do
        read -e -p "Start ripping ${CHAPTERS[$TITLE]} audio tracks from DVD title $TITLE? [Y/n] " CONT
        [[ -z $CONT ]] && CONT="y"
        if [[ $CONT =~ ^[yY]$ ]]; then
            break
        else
            exit 1
        fi
    done

echo

for (( i=1; i<=${CHAPTERS[$TITLE]}; i++ )); do
    if [[ $i -lt 10 ]]; then
        TRACKNO="0${i}"
    else
        TRACKNO="${i}"
    fi
    transcode -x null,dvd -y null,tcaud -i ${DVDDEV} -T $TITLE,${i},1 \
              -a ${AUDIOTRACK} -E 44100,16,2 --lame_preset ${LAME_PRESET} \
              -m ${OUTDIR}/${TRACKNO}.mp3
done

eject ${DVDDEV}
